apiVersion: v1
kind: Pod
metadata:
  name: alpha
  labels:
    env: test
spec:
  containers:
  - name: alpha
    image: redis
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "app_type"
    operator: "Exists"
    effect: "NoSchedule"
